monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "alsa_output.pci-0000_41_00.7.analog-stereo"
      }
    ]
    actions = {
      update-props = {
        priority.driver = 1100
        priority.session = 1100
      }
    }
  },
  {
    matches = [
      {
        node.name = "alsa_output.usb-Generic_USB_Audio-00.analog-stereo"
      }
    ]
    actions = {
      update-props = {
        priority.driver = 1000
        priority.session = 1000
      }
    }
  }
]
