[shell]
bash_indicator = '  '
fish_indicator = ''
style = 'bold bright-green'
format = '[$indicator]($style)'
disabled = false

[container]
symbol = '🥡'
style = 'bold bright-red'
format = '[$symbol $name ]($style)'
