# Terminal Setup
set -g default-terminal "screen-256color"

set-option -g prefix C-a

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# vim-like pane bindings
bind j select-pane -D
bind k select-pane -U
bind h select-pane -L
bind l select-pane -R

# Set up Powerline
run-shell "powerline-daemon -q"
source /usr/local/lib/python2.7/site-packages/powerline/bindings/tmux/powerline.conf
